class CanError(Exception): pass
class NoData(Exception): pass

